-- ==============================================================================
-- Clan Bank Manager (CBM) - Production Supabase PostgreSQL Schema
-- ==============================================================================
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard)
-- to initialize or migrate the complete CBM treasury, ledger, loan, marketplace,
-- and telemetry tables idempotently.
-- ==============================================================================

-- -----------------------------------------------------------------------------
-- 1. REGISTERED CLAN MEMBER ACCOUNTS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_accounts (
    account_name TEXT PRIMARY KEY,
    display_name TEXT,
    password_hash TEXT,
    password_salt TEXT,
    primary_territorial_account TEXT,
    avatar_url TEXT DEFAULT 'https://api.dicebear.com/7.x/identicon/svg?seed=cbm-guest',
    clan_tag TEXT DEFAULT 'ANTI-OG',
    role TEXT DEFAULT 'member',
    deposited_cents BIGINT DEFAULT 0,
    total_deposited_cents BIGINT DEFAULT 0,
    total_withdrawn_cents BIGINT DEFAULT 0,
    pin_hash TEXT,
    salt TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    referred_by TEXT,
    is_delinquent BOOLEAN DEFAULT FALSE,
    cbm_plus_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Backward compatibility columns for pre-existing databases
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS password_salt TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS primary_territorial_account TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT 'https://api.dicebear.com/7.x/identicon/svg?seed=cbm-guest';
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS clan_tag TEXT DEFAULT 'ANTI-OG';
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'member';
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS deposited_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS total_deposited_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS total_withdrawn_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS pin_hash TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS salt TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS referred_by TEXT;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS is_delinquent BOOLEAN DEFAULT FALSE;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS cbm_plus_until TIMESTAMPTZ;
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_cbm_accounts_cbm_plus_until ON public.cbm_accounts (cbm_plus_until);

-- -----------------------------------------------------------------------------
-- 2. DOUBLE-ENTRY ACCOUNTING LEDGER
-- (Note: Foreign key to cbm_accounts is omitted so that system-level entries like
--  'TREASURY' and 'reserves' do not trigger constraint violations)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL,
    entry_type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    balance_after_cents BIGINT NOT NULL,
    tx_hash TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS account_name TEXT;
ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS entry_type TEXT;
ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS amount_cents BIGINT;
ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS balance_after_cents BIGINT;
ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS tx_hash TEXT;
ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.cbm_ledger ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- Drop legacy foreign key constraint if it exists from older installations
ALTER TABLE public.cbm_ledger DROP CONSTRAINT IF EXISTS cbm_ledger_account_name_fkey;

-- -----------------------------------------------------------------------------
-- 3. CENTRAL TREASURY & RESERVE ACCOUNTING (Singleton row id = 1)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_treasury (
    id INT PRIMARY KEY DEFAULT 1,
    vault_account_name TEXT DEFAULT 'DdcBC',
    vault_total_gold_cents BIGINT DEFAULT 0,
    member_liabilities_cents BIGINT DEFAULT 0,
    bank_reserves_cents BIGINT DEFAULT 0,
    unencumbered_capital_cents BIGINT DEFAULT 0,
    loan_penalties_cents BIGINT DEFAULT 0,
    audit_status TEXT DEFAULT 'VERIFIED_LIVE',
    last_sync_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_treasury_row CHECK (id = 1)
);

ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS vault_account_name TEXT DEFAULT 'DdcBC';
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS vault_total_gold_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS member_liabilities_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS bank_reserves_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS unencumbered_capital_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS loan_penalties_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS audit_status TEXT DEFAULT 'VERIFIED_LIVE';
ALTER TABLE public.cbm_treasury ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 4. RECONCILED EXTERNAL TRANSACTION LEDGER (Replay Protection)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_processed_txs (
    tx_id TEXT PRIMARY KEY,
    timestamp_ms BIGINT NOT NULL,
    sender TEXT NOT NULL,
    receiver TEXT NOT NULL,
    amount_gold NUMERIC NOT NULL,
    fee_gold NUMERIC NOT NULL,
    credited_account TEXT,
    processed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS timestamp_ms BIGINT;
ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS sender TEXT;
ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS receiver TEXT;
ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS amount_gold NUMERIC;
ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS fee_gold NUMERIC;
ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS credited_account TEXT;
ALTER TABLE public.cbm_processed_txs ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 5. WITHDRAWAL REQUESTS & EXECUTION QUEUE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL,
    target_account TEXT NOT NULL,
    amount_gold INT NOT NULL,
    fee_cents BIGINT DEFAULT 0,
    status TEXT DEFAULT 'PENDING',
    approved_by TEXT,
    tx_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    executed_at TIMESTAMPTZ
);

ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS account_name TEXT;
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS target_account TEXT;
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS amount_gold INT;
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS fee_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'PENDING';
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS tx_id TEXT;
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_withdrawals ADD COLUMN IF NOT EXISTS executed_at TIMESTAMPTZ;

-- -----------------------------------------------------------------------------
-- 6. MEMBER LOAN FACILITIES (BIGINT primary key matching Python integer IDs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL,
    principal_gold INT NOT NULL,
    interest_rate_percent NUMERIC DEFAULT 0.0,
    penalty_interest_rate NUMERIC DEFAULT 50.0,
    term_days INT DEFAULT 14,
    due_at TIMESTAMPTZ,
    repaid_cents BIGINT DEFAULT 0,
    penalty_cents BIGINT DEFAULT 0,
    status TEXT DEFAULT 'ACTIVE',
    borrower_territorial_account TEXT,
    credential_status TEXT DEFAULT 'VALID',
    last_credential_check_at TIMESTAMPTZ,
    seizure_attempts INT DEFAULT 0,
    last_seizure_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safe migration if cbm_loans.id was previously defined as UUID
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'cbm_loans' 
          AND column_name = 'id' 
          AND data_type = 'uuid'
    ) THEN
        ALTER TABLE public.cbm_loans DROP CONSTRAINT IF EXISTS cbm_loans_pkey CASCADE;
        ALTER TABLE public.cbm_loans RENAME COLUMN id TO old_uuid_id;
        ALTER TABLE public.cbm_loans ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
        ALTER TABLE public.cbm_loans DROP COLUMN old_uuid_id;
    END IF;
END $$;

ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS penalty_interest_rate NUMERIC DEFAULT 50.0;
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS penalty_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS borrower_territorial_account TEXT;
-- Zero-Knowledge Cloud Isolation: Purge credentials from cloud Supabase
ALTER TABLE public.cbm_loans DROP COLUMN IF EXISTS territorial_password;
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS credential_status TEXT DEFAULT 'VALID';
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS last_credential_check_at TIMESTAMPTZ;
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS seizure_attempts INT DEFAULT 0;
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS last_seizure_attempt_at TIMESTAMPTZ;
ALTER TABLE public.cbm_loans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 7. LINKED TERRITORIAL.IO PAYMENT METHODS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cbm_username TEXT NOT NULL,
    territorial_account_name TEXT NOT NULL UNIQUE,
    display_name TEXT,
    verification_type TEXT NOT NULL DEFAULT 'INPUT_CREDENTIALS',
    status TEXT NOT NULL DEFAULT 'VERIFIED',
    is_primary BOOLEAN DEFAULT FALSE,
    total_transacted_gold NUMERIC DEFAULT 0,
    linked_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ DEFAULT NOW()
);

-- Zero-Knowledge Cloud Isolation: Purge credentials from cloud Supabase
ALTER TABLE public.cbm_payment_methods DROP COLUMN IF EXISTS territorial_password;
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS verification_type TEXT DEFAULT 'INPUT_CREDENTIALS';
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'VERIFIED';
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT FALSE;
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS total_transacted_gold NUMERIC DEFAULT 0;
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS linked_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_payment_methods ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 8. CLAN WAR CHEST & TREASURY DONATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_name TEXT NOT NULL,
    territorial_account TEXT,
    amount_gold NUMERIC(12, 2) NOT NULL,
    amount_cents BIGINT NOT NULL,
    message TEXT,
    source TEXT DEFAULT 'BALANCE',
    tx_hash TEXT,
    is_refundable BOOLEAN DEFAULT FALSE NOT NULL,
    status TEXT DEFAULT 'IRREVOCABLE' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS donor_name TEXT;
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS territorial_account TEXT;
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS amount_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS amount_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS message TEXT DEFAULT '';
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'BALANCE';
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS tx_hash TEXT;
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS is_refundable BOOLEAN DEFAULT FALSE;
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'IRREVOCABLE';
ALTER TABLE public.cbm_donations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 9. MODEL 3: WEB-DECLARED IN-GAME DONATION SLIPS (TEXT id to support "slip_...")
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_pending_donations (
    id TEXT PRIMARY KEY,
    account_name TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    amount_gold NUMERIC(12, 2) NOT NULL,
    message TEXT DEFAULT '',
    status TEXT DEFAULT 'PENDING',
    tx_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '15 minutes')
);

-- Safe migration if cbm_pending_donations.id was created as UUID
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'cbm_pending_donations' 
          AND column_name = 'id' 
          AND data_type = 'uuid'
    ) THEN
        ALTER TABLE public.cbm_pending_donations DROP CONSTRAINT IF EXISTS cbm_pending_donations_pkey CASCADE;
        ALTER TABLE public.cbm_pending_donations ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE public.cbm_pending_donations ALTER COLUMN id TYPE TEXT USING id::text;
        ALTER TABLE public.cbm_pending_donations ADD PRIMARY KEY (id);
    END IF;
END $$;

ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS account_name TEXT;
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS amount_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS amount_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS message TEXT DEFAULT '';
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'PENDING';
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS tx_hash TEXT;
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_pending_donations ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '15 minutes');

-- -----------------------------------------------------------------------------
-- 10. VAULT BALANCE & LIQUIDITY SNAPSHOTS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_vault_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp_epoch NUMERIC(16, 4) NOT NULL,
    vault_total_gold NUMERIC(14, 2) NOT NULL,
    unencumbered_reserves_gold NUMERIC(14, 2) NOT NULL,
    member_liabilities_gold NUMERIC(14, 2) NOT NULL,
    inflow_period_gold NUMERIC(14, 2) DEFAULT 0.0,
    outflow_period_gold NUMERIC(14, 2) DEFAULT 0.0,
    net_flow_gold NUMERIC(14, 2) DEFAULT 0.0,
    tx_count_period INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS timestamp_epoch NUMERIC(16, 4);
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS vault_total_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS unencumbered_reserves_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS member_liabilities_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS inflow_period_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS outflow_period_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS net_flow_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS tx_count_period INT DEFAULT 0;
ALTER TABLE public.cbm_vault_snapshots ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 11. ADMIN ELECTION CAMPAIGN & VOTE REWARDS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_admin_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id TEXT UNIQUE NOT NULL,
    cbm_username TEXT NOT NULL,
    voter_account TEXT NOT NULL,
    target_account TEXT NOT NULL DEFAULT 'DdcBC',
    votes_count INT NOT NULL,
    gold_spent NUMERIC(12, 2) NOT NULL,
    reward_gold NUMERIC(12, 2) NOT NULL,
    reward_cents BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    quarantine_until TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    baseline_admin_points INT DEFAULT 0,
    rejection_reason TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS voter_account TEXT;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS cbm_username TEXT;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS target_account TEXT DEFAULT 'DdcBC';
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS votes_count INT DEFAULT 0;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS gold_spent NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS reward_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS reward_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'PENDING';
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS quarantine_until TIMESTAMPTZ;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS baseline_admin_points INT DEFAULT 0;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
ALTER TABLE public.cbm_admin_votes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 12. PRODUCT MARKETPLACE & PAYMENT GATEWAY
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT UNIQUE NOT NULL,
    owner_account TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    price_gold NUMERIC(12, 2) NOT NULL,
    price_cents BIGINT NOT NULL,
    callback_url TEXT NOT NULL,
    webhook_url TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    sales_count INT DEFAULT 0,
    total_revenue_gold NUMERIC(12, 2) DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS product_id TEXT;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS owner_account TEXT DEFAULT 'DdcBC';
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS name TEXT DEFAULT 'Product';
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS price_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS price_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS callback_url TEXT DEFAULT '';
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS webhook_url TEXT;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE';
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS sales_count INT DEFAULT 0;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS total_revenue_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS requires_client_verification INT DEFAULT 0;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS requirement_meta JSONB DEFAULT NULL;
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.cbm_product_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    product_id TEXT NOT NULL,
    buyer_cbm_username TEXT,
    buyer_territorial_account TEXT,
    price_gold NUMERIC(12, 2) NOT NULL,
    price_cents BIGINT NOT NULL,
    owner_share_cents BIGINT NOT NULL,
    cushion_share_cents BIGINT NOT NULL,
    payment_method TEXT NOT NULL,
    tx_hash TEXT,
    verification_token TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMPTZ NOT NULL,
    fulfilled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cbm_product_attestations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES public.cbm_products(product_id) ON DELETE CASCADE,
    account_name TEXT NOT NULL,
    client_id TEXT NOT NULL,
    attestation_token TEXT UNIQUE NOT NULL,
    attestation_payload JSONB,
    verified_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cbm_attestations_lookup ON public.cbm_product_attestations(product_id, account_name, expires_at);
CREATE INDEX IF NOT EXISTS idx_cbm_attestations_token ON public.cbm_product_attestations(attestation_token);


ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS order_id TEXT;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS product_id TEXT;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS buyer_cbm_username TEXT;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS buyer_territorial_account TEXT;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS price_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS price_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS owner_share_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS cushion_share_cents BIGINT DEFAULT 0;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'IN_GAME';
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS tx_hash TEXT;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS verification_token TEXT;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'PENDING';
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '15 minutes');
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS fulfilled_at TIMESTAMPTZ;
ALTER TABLE public.cbm_product_orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 13. REFERRAL PROGRAM
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_referrals (
    id BIGSERIAL PRIMARY KEY,
    inviter_account TEXT NOT NULL,
    invitee_account TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    invitee_donated_gold NUMERIC(14, 2) DEFAULT 0.0,
    invitee_deposited_gold NUMERIC(14, 2) DEFAULT 0.0,
    reward_gold NUMERIC(14, 2) DEFAULT 0.0,
    tier1_rewarded_at TIMESTAMPTZ,
    tier2_rewarded_at TIMESTAMPTZ,
    tier3_rewarded_at TIMESTAMPTZ,
    perpetual_commission_gold NUMERIC(14, 2) DEFAULT 0.0,
    rewarded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS inviter_account TEXT;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS invitee_account TEXT;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'PENDING';
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS invitee_donated_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS invitee_deposited_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS reward_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS tier1_rewarded_at TIMESTAMPTZ;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS tier2_rewarded_at TIMESTAMPTZ;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS tier3_rewarded_at TIMESTAMPTZ;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS perpetual_commission_gold NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS rewarded_at TIMESTAMPTZ;
ALTER TABLE public.cbm_referrals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 14. SPONSORSHIPS & ADVERTISING ENGINE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_sponsorship_slots (
    slot_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    base_price_cents BIGINT NOT NULL,
    current_price_cents BIGINT NOT NULL,
    max_active_sponsors INT DEFAULT 1,
    active_sponsor_account TEXT,
    lease_start_ts TIMESTAMPTZ,
    lease_end_ts TIMESTAMPTZ,
    is_available BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS base_price_cents BIGINT DEFAULT 50000;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS current_price_cents BIGINT DEFAULT 50000;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS max_active_sponsors INT DEFAULT 1;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS active_sponsor_account TEXT;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS lease_start_ts TIMESTAMPTZ;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS lease_end_ts TIMESTAMPTZ;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;
ALTER TABLE public.cbm_sponsorship_slots ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.cbm_sponsored_ads (
    ad_id TEXT PRIMARY KEY,
    slot_id TEXT NOT NULL,
    owner_account TEXT NOT NULL,
    title TEXT NOT NULL,
    tagline TEXT NOT NULL,
    target_url TEXT NOT NULL,
    badge_text TEXT DEFAULT 'PROMOTED',
    image_url TEXT,
    image_width INT DEFAULT 728,
    image_height INT DEFAULT 90,
    is_official BOOLEAN DEFAULT FALSE,
    priority INT DEFAULT 0,
    impressions BIGINT DEFAULT 0,
    clicks BIGINT DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'ACTIVE'
);

ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS slot_id TEXT;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS owner_account TEXT DEFAULT 'DdcBC';
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS title TEXT DEFAULT 'Featured Partner';
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS tagline TEXT DEFAULT '';
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS target_url TEXT DEFAULT '#';
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS badge_text TEXT DEFAULT 'PROMOTED';
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS image_width INT DEFAULT 728;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS image_height INT DEFAULT 90;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS is_official BOOLEAN DEFAULT FALSE;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS priority INT DEFAULT 0;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS impressions BIGINT DEFAULT 0;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS clicks BIGINT DEFAULT 0;
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days');
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_sponsored_ads ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE';

CREATE TABLE IF NOT EXISTS public.cbm_ad_publishers (
    id BIGSERIAL PRIMARY KEY,
    publisher_account TEXT UNIQUE NOT NULL,
    app_name TEXT NOT NULL,
    total_impressions BIGINT DEFAULT 0,
    total_clicks BIGINT DEFAULT 0,
    total_onboarded_members INT DEFAULT 0,
    total_gold_earned NUMERIC(14, 2) DEFAULT 0.0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS app_name TEXT DEFAULT 'External App';
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS total_impressions BIGINT DEFAULT 0;
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS total_clicks BIGINT DEFAULT 0;
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS total_onboarded_members INT DEFAULT 0;
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS total_gold_earned NUMERIC(14, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_ad_publishers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 15. DEVELOPER API KEYS & TELEMETRY (is_active BOOLEAN to support Python True/False)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id TEXT UNIQUE NOT NULL,
    key_hash TEXT UNIQUE NOT NULL,
    key_prefix TEXT NOT NULL,
    app_name TEXT NOT NULL,
    owner_account TEXT NOT NULL,
    environment TEXT DEFAULT 'live',
    scopes TEXT DEFAULT 'read:bank,read:members',
    rate_limit_rpm INT DEFAULT 60,
    total_requests INT DEFAULT 0,
    credits_consumed_gold NUMERIC(12, 2) DEFAULT 0.0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS key_id TEXT;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS key_hash TEXT;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS key_prefix TEXT;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS app_name TEXT;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS owner_account TEXT DEFAULT 'DdcBC';
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS environment TEXT DEFAULT 'live';
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS scopes TEXT DEFAULT 'read:bank,read:members';
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS rate_limit_rpm INT DEFAULT 60;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS total_requests INT DEFAULT 0;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS credits_consumed_gold NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_api_keys ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ;

-- Migrate is_active from INTEGER to BOOLEAN if needed
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'cbm_api_keys' 
          AND column_name = 'is_active' 
          AND data_type = 'integer'
    ) THEN
        ALTER TABLE public.cbm_api_keys ALTER COLUMN is_active DROP DEFAULT;
        ALTER TABLE public.cbm_api_keys ALTER COLUMN is_active TYPE BOOLEAN USING (is_active != 0);
        ALTER TABLE public.cbm_api_keys ALTER COLUMN is_active SET DEFAULT TRUE;
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 16. BINARY ASSET STORAGE (For standalone headless textures/products)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_assets (
    filename TEXT PRIMARY KEY,
    subfolder TEXT NOT NULL DEFAULT 'products',
    mime_type TEXT NOT NULL,
    data BYTEA NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_assets ADD COLUMN IF NOT EXISTS subfolder TEXT DEFAULT 'products';
ALTER TABLE public.cbm_assets ADD COLUMN IF NOT EXISTS mime_type TEXT DEFAULT 'application/octet-stream';
ALTER TABLE public.cbm_assets ADD COLUMN IF NOT EXISTS data BYTEA;
ALTER TABLE public.cbm_assets ADD COLUMN IF NOT EXISTS size_bytes BIGINT DEFAULT 0;
ALTER TABLE public.cbm_assets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_assets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 17. CHAT WHITELIST (Authorized Operator Access)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cbm_chat_whitelist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT UNIQUE NOT NULL,
    added_by TEXT NOT NULL DEFAULT 'SYSTEM',
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cbm_chat_whitelist ADD COLUMN IF NOT EXISTS added_by TEXT DEFAULT 'SYSTEM';
ALTER TABLE public.cbm_chat_whitelist ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.cbm_chat_whitelist ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE public.cbm_chat_whitelist ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_chat_whitelist ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- -----------------------------------------------------------------------------
-- 18. FEDERATED OIDC IDENTITIES & VIRTUAL CREDIT METERING
-- -----------------------------------------------------------------------------
-- Federated External Identities (OIDC Accounts)
CREATE TABLE IF NOT EXISTS public.cbm_user_identities (
    id BIGSERIAL PRIMARY KEY,
    account_name TEXT NOT NULL REFERENCES public.cbm_accounts(account_name) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    provider_sub TEXT NOT NULL,
    email TEXT,
    email_verified BOOLEAN DEFAULT FALSE,
    profile_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_provider_sub UNIQUE (provider, provider_sub)
);

CREATE INDEX IF NOT EXISTS idx_cbm_identities_user ON public.cbm_user_identities (account_name);
CREATE INDEX IF NOT EXISTS idx_cbm_identities_lookup ON public.cbm_user_identities (provider, provider_sub);

ALTER TABLE public.cbm_user_identities ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.cbm_user_identities ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE public.cbm_user_identities ADD COLUMN IF NOT EXISTS profile_data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.cbm_user_identities ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cbm_user_identities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();


-- -----------------------------------------------------------------------------
-- 19. AUTOMATED SCHEMA NORMALIZATIONS & CONSTRAINTS RELAXATION
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    rec RECORD;
BEGIN
    -- Synchronize legacy slot_name column in cbm_sponsorship_slots if present
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'cbm_sponsorship_slots' 
          AND column_name = 'slot_name'
    ) THEN
        ALTER TABLE public.cbm_sponsorship_slots ALTER COLUMN slot_name DROP NOT NULL;
        ALTER TABLE public.cbm_sponsorship_slots ALTER COLUMN slot_name SET DEFAULT '';
        UPDATE public.cbm_sponsorship_slots SET name = COALESCE(name, slot_name, 'Slot');
        UPDATE public.cbm_sponsorship_slots SET slot_name = COALESCE(slot_name, name, '');
    END IF;

    -- Drop obsolete NOT NULL constraints on non-key columns to prevent insert errors
    FOR rec IN 
        SELECT table_name, column_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name IN (
              'cbm_sponsorship_slots', 'cbm_sponsored_ads', 'cbm_products', 
              'cbm_product_orders', 'cbm_api_keys', 'cbm_admin_votes', 
              'cbm_accounts', 'cbm_ledger', 'cbm_loans', 'cbm_payment_methods',
              'cbm_donations', 'cbm_pending_donations', 'cbm_referrals'
          )
          AND is_nullable = 'NO'
          AND column_default IS NULL
          AND column_name NOT IN (
              'id', 'slot_id', 'ad_id', 'product_id', 'order_id', 
              'key_id', 'key_hash', 'claim_id', 'account_name', 'tx_id',
              'territorial_account_name', 'filename'
          )
    LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I DROP NOT NULL', rec.table_name, rec.column_name);
    END LOOP;

    -- Ensure all timestamp columns across all tables are normalized to TIMESTAMPTZ
    FOR rec IN 
        SELECT table_name, column_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name IN (
              'cbm_sponsorship_slots', 'cbm_sponsored_ads', 'cbm_products', 
              'cbm_product_orders', 'cbm_api_keys', 'cbm_admin_votes', 
              'cbm_accounts', 'cbm_ledger', 'cbm_loans', 'cbm_payment_methods',
              'cbm_donations', 'cbm_pending_donations', 'cbm_referrals',
              'cbm_withdrawals', 'cbm_vault_snapshots', 'cbm_treasury', 'cbm_assets'
          )
          AND column_name IN (
              'updated_at', 'created_at', 'expires_at', 'fulfilled_at', 
              'lease_start_ts', 'lease_end_ts', 'last_used_at', 
              'quarantine_until', 'verified_at', 'due_at', 'linked_at',
              'tier1_rewarded_at', 'tier2_rewarded_at', 'tier3_rewarded_at', 'rewarded_at',
              'last_sync_at', 'executed_at', 'last_credential_check_at', 'last_seizure_attempt_at'
          )
          AND data_type NOT IN ('timestamp with time zone', 'timestamp without time zone')
    LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I DROP DEFAULT', rec.table_name, rec.column_name);
        EXECUTE format(
            'ALTER TABLE public.%I ALTER COLUMN %I TYPE TIMESTAMPTZ USING CASE WHEN %I IS NULL THEN NULL WHEN %I::double precision > 1000000000 THEN to_timestamp(%I::double precision) ELSE NOW() END',
            rec.table_name, rec.column_name, rec.column_name, rec.column_name, rec.column_name
        );
        IF rec.column_name IN ('created_at', 'updated_at') THEN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET DEFAULT NOW()', rec.table_name, rec.column_name);
        END IF;
    END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- 18. HIGH-CONCURRENCY INDEXES
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_cbm_ledger_account ON public.cbm_ledger (account_name);
CREATE INDEX IF NOT EXISTS idx_cbm_ledger_created ON public.cbm_ledger (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cbm_processed_txs_sender ON public.cbm_processed_txs (sender);
CREATE INDEX IF NOT EXISTS idx_cbm_processed_txs_receiver ON public.cbm_processed_txs (receiver);
CREATE INDEX IF NOT EXISTS idx_cbm_processed_txs_ts ON public.cbm_processed_txs (timestamp_ms DESC);

CREATE INDEX IF NOT EXISTS idx_cbm_withdrawals_status ON public.cbm_withdrawals (status);
CREATE INDEX IF NOT EXISTS idx_cbm_withdrawals_acc ON public.cbm_withdrawals (account_name);

CREATE INDEX IF NOT EXISTS idx_cbm_loans_acc ON public.cbm_loans (account_name);
CREATE INDEX IF NOT EXISTS idx_cbm_loans_status ON public.cbm_loans (status);

CREATE INDEX IF NOT EXISTS idx_cbm_pm_username ON public.cbm_payment_methods (cbm_username);
CREATE INDEX IF NOT EXISTS idx_cbm_pm_terri_acc ON public.cbm_payment_methods (territorial_account_name);

CREATE INDEX IF NOT EXISTS idx_cbm_donations_donor ON public.cbm_donations (donor_name);
CREATE INDEX IF NOT EXISTS idx_cbm_donations_created ON public.cbm_donations (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cbm_pending_donations_lookup ON public.cbm_pending_donations (account_name, amount_cents, status);

CREATE INDEX IF NOT EXISTS idx_cbm_vault_snapshots_ts ON public.cbm_vault_snapshots (timestamp_epoch DESC);

CREATE INDEX IF NOT EXISTS idx_cbm_admin_votes_voter ON public.cbm_admin_votes (voter_account);
CREATE INDEX IF NOT EXISTS idx_cbm_admin_votes_user ON public.cbm_admin_votes (cbm_username);
CREATE INDEX IF NOT EXISTS idx_cbm_admin_votes_status ON public.cbm_admin_votes (status);

CREATE INDEX IF NOT EXISTS idx_cbm_products_owner ON public.cbm_products (owner_account);
CREATE INDEX IF NOT EXISTS idx_cbm_products_status ON public.cbm_products (status);

CREATE INDEX IF NOT EXISTS idx_cbm_product_orders_prod ON public.cbm_product_orders (product_id);
CREATE INDEX IF NOT EXISTS idx_cbm_product_orders_status ON public.cbm_product_orders (status);
CREATE INDEX IF NOT EXISTS idx_cbm_product_orders_token ON public.cbm_product_orders (verification_token);

CREATE INDEX IF NOT EXISTS idx_cbm_referrals_inviter ON public.cbm_referrals (inviter_account);
CREATE INDEX IF NOT EXISTS idx_cbm_referrals_invitee ON public.cbm_referrals (invitee_account);

CREATE INDEX IF NOT EXISTS idx_cbm_sponsored_ads_slot ON public.cbm_sponsored_ads (slot_id, status);
CREATE INDEX IF NOT EXISTS idx_cbm_sponsored_ads_owner ON public.cbm_sponsored_ads (owner_account);
CREATE INDEX IF NOT EXISTS idx_cbm_sponsored_ads_official ON public.cbm_sponsored_ads (slot_id, is_official, status);

CREATE INDEX IF NOT EXISTS idx_cbm_ad_publishers_acc ON public.cbm_ad_publishers (publisher_account);

CREATE INDEX IF NOT EXISTS idx_cbm_api_keys_hash ON public.cbm_api_keys (key_hash);
CREATE INDEX IF NOT EXISTS idx_cbm_api_keys_owner ON public.cbm_api_keys (owner_account);

CREATE INDEX IF NOT EXISTS idx_cbm_assets_subfolder ON public.cbm_assets (subfolder);

-- -----------------------------------------------------------------------------
-- 19. ROW LEVEL SECURITY (RLS) POLICIES
-- Enables Row Level Security on all tables and creates comprehensive policies
-- allowing anon/authenticated read-only access and full service_role access.
-- -----------------------------------------------------------------------------
ALTER TABLE public.cbm_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_treasury ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_processed_txs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_pending_donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_vault_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_admin_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_product_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_sponsorship_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_sponsored_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_ad_publishers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbm_chat_whitelist ENABLE ROW LEVEL SECURITY;

-- 19a. Strict Row Level Security Policies (Zero-Knowledge Isolation)
DO $$
DECLARE
    tbl text;
    -- Public telemetry tables: Safe for anonymous and authenticated read access
    public_tables text[] := ARRAY[
        'cbm_vault_snapshots', 'cbm_sponsorship_slots', 'cbm_sponsored_ads', 
        'cbm_assets', 'cbm_products'
    ];
    -- Sensitive member & treasury tables: Access strictly restricted to backend service_role
    sensitive_tables text[] := ARRAY[
        'cbm_accounts', 'cbm_ledger', 'cbm_treasury', 'cbm_processed_txs',
        'cbm_withdrawals', 'cbm_loans', 'cbm_payment_methods', 'cbm_donations',
        'cbm_pending_donations', 'cbm_admin_votes', 'cbm_product_orders', 
        'cbm_referrals', 'cbm_ad_publishers', 'cbm_api_keys', 'cbm_chat_whitelist',
        'cbm_user_identities'
    ];
BEGIN
    -- 1. Configure Public Telemetry Tables (Read-only for public, managed by service_role)
    FOREACH tbl IN ARRAY public_tables LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Allow public read ' || tbl, tbl);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO anon, authenticated USING (TRUE)', 'Allow public read ' || tbl, tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Service role manage ' || tbl, tbl);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE)', 'Service role manage ' || tbl, tbl);
    END LOOP;

    -- 2. Lockdown Sensitive Tables (Revoke ALL public/anon read access; service_role ONLY)
    FOREACH tbl IN ARRAY sensitive_tables LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Allow public read ' || tbl, tbl);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Public read ' || tbl, tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Service role manage ' || tbl, tbl);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE)', 'Service role manage ' || tbl, tbl);
    END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- 20. SEED ESSENTIAL SYSTEM ACCOUNTS, SINGLETON ROWS & DEFAULT ASSETS
-- -----------------------------------------------------------------------------
-- System accounts to ensure foreign keys never fail
INSERT INTO public.cbm_accounts (account_name, display_name, clan_tag, role, deposited_cents, cbm_plus_until)
VALUES 
    ('DdcBC', 'DdcBC Vault', 'ANTI-OG', 'system', 0, '2100-01-01 00:00:00+00'),
    ('B8bbq', 'B8bbq', 'ANTI-OG', 'admin', 0, '2100-01-01 00:00:00+00'),
    ('TREASURY', 'Clan Central Treasury', 'ANTI-OG', 'system', 0, '2100-01-01 00:00:00+00'),
    ('reserves', 'Bank Reserves Pool', 'ANTI-OG', 'system', 0, '2100-01-01 00:00:00+00'),
    ('war_chest', 'Clan War Chest', 'ANTI-OG', 'system', 0, '2100-01-01 00:00:00+00')
ON CONFLICT (account_name) DO UPDATE SET 
    role = EXCLUDED.role,
    cbm_plus_until = COALESCE(EXCLUDED.cbm_plus_until, cbm_accounts.cbm_plus_until);

-- Initialize Treasury Singleton
INSERT INTO public.cbm_treasury (
    id, vault_account_name, vault_total_gold_cents, member_liabilities_cents, 
    bank_reserves_cents, unencumbered_capital_cents, loan_penalties_cents
) VALUES (1, 'DdcBC', 0, 0, 0, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- Seed default high-traffic sponsorship slots
INSERT INTO public.cbm_sponsorship_slots (
    slot_id, name, description, base_price_cents, current_price_cents, max_active_sponsors, is_available
) VALUES
    ('SLOT_HERO', 'Clan Vault Header Banner', 'Prime billboard directly above real-time clan liquidity telemetry.', 50000, 50000, 1, TRUE),
    ('SLOT_TELEMETRY', 'Transaction Ledger Sponsored Feed', 'Inline banner embedded within the high-frequency transaction stream.', 25000, 25000, 1, TRUE),
    ('SLOT_DISCORD', 'Developer Hub Spotlight', 'Featured interactive showcase on developer integration portal.', 35000, 35000, 1, TRUE)
ON CONFLICT (slot_id) DO NOTHING;

-- Seed canonical merchant products
INSERT INTO public.cbm_products (
    product_id, owner_account, name, description, image_url,
    price_gold, price_cents, callback_url, status, sales_count, total_revenue_gold,
    requires_client_verification, requirement_meta
) VALUES 
    ('prod_hellokitty', 'B8bbq', 'Hello Kitty Territory Pattern', 'High-fidelity seamless texture coating player territory during live matches.', '/assets/patterns/hello-kitty-pattern.png', 500.0, 50000, 'https://pogxelqari.github.io/TerriX/client/', 'ACTIVE', 0, 0.0, 0, NULL),
    ('prod_poland', 'B8bbq', 'Poland Flag Territory Pattern', 'Official Polish national coat of arms territory pattern for TerriX Client.', '/assets/products/poland-pattern.avif', 1000.0, 100000, 'https://pogxelqari.github.io/TerriX/client/', 'ACTIVE', 0, 0.0, 0, NULL),
    ('prod_kilr', 'B8bbq', '[KILR] Clan Territory Pattern', 'Official KILR Clan Logo territory pattern for TerriX Client. Free to equip with verified client requirement.', '/assets/patterns/kilr-clanlogo-pattern.png', 0.0, 0, 'https://pogxelqari.github.io/TerriX/client/', 'ACTIVE', 0, 0.0, 1, '{"description": "Client verified clan requirement", "attestation_ttl": 3600}'::jsonb)
ON CONFLICT (product_id) DO NOTHING;



-- Seed official TerriX client API key (cbm_live_2063e984d4e66cbd90cc1fcc33e54a1199d5a978)
INSERT INTO public.cbm_api_keys (
    key_id, key_hash, key_prefix, app_name, owner_account,
    environment, scopes, rate_limit_rpm, total_requests,
    credits_consumed_gold, is_active
) VALUES (
    'key_terrix_official',
    encode(sha256('cbm_live_2063e984d4e66cbd90cc1fcc33e54a1199d5a978'::bytea), 'hex'),
    'cbm_live_2063...a978',
    'TerriX Official Client',
    'B8bbq',
    'live',
    'read:bank,read:members,read:loans,read:products,write:products,write:donations,admin',
    600,
    0,
    0.0,
    TRUE
) ON CONFLICT (key_id) DO NOTHING;

-- Seed default chat whitelist entry
INSERT INTO public.cbm_chat_whitelist (account_name, added_by, is_active, notes)
VALUES ('B8bbq', 'SYSTEM', TRUE, 'Clan Founder & System Admin')
ON CONFLICT (account_name) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 15. INVITE SYSTEM & CBM PLUS SUBSCRIPTIONS
-- -----------------------------------------------------------------------------
ALTER TABLE public.cbm_accounts ADD COLUMN IF NOT EXISTS cbm_plus_until TIMESTAMPTZ DEFAULT NULL;

CREATE TABLE IF NOT EXISTS public.cbm_invites (
    code_id TEXT PRIMARY KEY,
    inviter_account TEXT NOT NULL REFERENCES public.cbm_accounts(account_name) ON DELETE CASCADE,
    max_uses INTEGER NOT NULL DEFAULT 1,
    uses_count INTEGER NOT NULL DEFAULT 0,
    cost_per_use_cents BIGINT NOT NULL DEFAULT 2500,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cbm_invites_inviter ON public.cbm_invites(inviter_account);
ALTER TABLE public.cbm_invites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage cbm_invites" ON public.cbm_invites;
CREATE POLICY "Service role manage cbm_invites" ON public.cbm_invites FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

CREATE TABLE IF NOT EXISTS public.cbm_invite_prospects (
    id BIGSERIAL PRIMARY KEY,
    prospect_token TEXT NOT NULL,
    invite_code TEXT NOT NULL REFERENCES public.cbm_invites(code_id) ON DELETE CASCADE,
    inviter_account TEXT NOT NULL REFERENCES public.cbm_accounts(account_name) ON DELETE CASCADE,
    client_ip_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Enforce strictly one code per inviter per prospect
    CONSTRAINT uq_prospect_per_inviter UNIQUE (prospect_token, inviter_account)
);
CREATE INDEX IF NOT EXISTS idx_cbm_prospects_token ON public.cbm_invite_prospects(prospect_token);
CREATE INDEX IF NOT EXISTS idx_cbm_prospects_inviter ON public.cbm_invite_prospects(inviter_account);
ALTER TABLE public.cbm_invite_prospects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage cbm_invite_prospects" ON public.cbm_invite_prospects;
CREATE POLICY "Service role manage cbm_invite_prospects" ON public.cbm_invite_prospects FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

CREATE TABLE IF NOT EXISTS public.cbm_pending_subscriptions (
    id TEXT PRIMARY KEY,
    account_name TEXT NOT NULL,
    amount_gold NUMERIC(12, 2) NOT NULL DEFAULT 500.00,
    amount_cents BIGINT NOT NULL DEFAULT 50000,
    status TEXT NOT NULL DEFAULT 'PENDING',
    tx_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '15 minutes')
);
CREATE INDEX IF NOT EXISTS idx_cbm_pending_sub_acc ON public.cbm_pending_subscriptions(account_name, status);
ALTER TABLE public.cbm_pending_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage cbm_pending_subscriptions" ON public.cbm_pending_subscriptions;
CREATE POLICY "Service role manage cbm_pending_subscriptions" ON public.cbm_pending_subscriptions FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

-- ==============================================================================
-- End of CBM Supabase Initialization Script
-- ==============================================================================
